baseURL: https://seq.jake.garden
languageCode: en-us
title: Jake's Logseq Garden
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Sup bruh 😎
    Content: This is a static subdomain consisting of markdown files exported from Loqseq and converted into a Hugo framework hosted through Cloudflare. These are my notes on various topics.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/Gronemeyer"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # name: "twitter"
    # url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Jake Gronemeyer"
  contact: "dcypheral@protonmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
